version: '3.8'

services:
  db:
    image: postgres:16
    container_name: fantasy-icl-postgres
    restart: always
    ports:
      - '5433:5432'
    environment:
      POSTGRES_DB: fantasyicldb
      POSTGRES_USER: fantasyicl_backend
      POSTGRES_PASSWORD: icl@2025
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "fantasyicl_backend", "-d", "fantasyicldb"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: fantasy_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: asnc1391@gmail.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin@123
    ports:
      - '5050:80'
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - pgadmin_data:/var/lib/pgadmin
volumes:
  pgdata:
  pgadmin_data: