spring:
  datasource:
    url: ${YOUR_DB}
    username: ${USERNAME}
    password: ${PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

app:
  jwtSecret: ${JWT_SECRET}
  jwtExpirationMs: 900000       # 15 minutes
  refreshTokenExpirationMs: 604800000  # 7 days
